key = "rick"
enigm = """
Je ne t'abandonnerai jamais
Je ne te laisserai jamais tomber
Je ne vais jamais courir et t'abandonner
Je ne te ferai jamais pleurer
Je ne dirai jamais au revoir
Je ne vais jamais mentir et te blesser

Quel est mon prénom ? 
"""